# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
encoding: utf-8
# Site settings
title: Ultrasev çš„åšå®¢
brief-intro: AIã€Tools & Life
baseurl: '' # the subpath of your site, e.g. /blog
url: 'https://www.ultrasev.com' # the base hostname & protocol for your site

permalink: /:year/:month/:day/:title/

# other links
twitter_username: ultrasev_
youtube_username: ultrasev
email: cyaeyz@gmail.com
weibo_username: 
facebook_username:
zhihu_username:
linkedIn_username:
dribbble_username:

description_footer: ğŸ’¡

# comments
# ä¸‰ç§è¯„è®ºæ’ä»¶ï¼Œé€‰ä¸€ä¸ªå°±å¥½äº†
# disqus_shortname: #slipper
gitalk:
  enable: false
#   clientID:
#   clientSecret:
#   repo:
#   owner: 
#   admin: 
utteranc_es:
  enable: true
  repo: 'ultrasev/ultrasev.github.io'
  issue-term: pathname
  theme: github-light

# èµèµ
# reward:
#   enable: true
#   wechat: /assets/wechat.png
  # alipay: /assets/images/reward/alipay.png

# statistic analysis ç»Ÿè®¡ä»£ç 
# ç™¾åº¦ç»Ÿè®¡ idï¼Œå°†ç»Ÿè®¡ä»£ç æ›¿æ¢ä¸ºè‡ªå·±çš„ç™¾åº¦ç»Ÿè®¡idï¼Œå³
# hm.src = "//hm.baidu.com/hm.js?xxxxxxxxxxxx";
# xxxxxå­—ç¬¦ä¸²
baidu_tongji_id: 80ef4ad13c36b61cc02574edb9a2938d
google_analytics_id: G-9GSKN6TWPL

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# port
# port: 1234

# url
category_dir: category/
tag_dir: tag/

# excerpt
excerpt_separator: "\n\n\n\n"

# paginate
plugins: [jekyll-paginate]
paginate: 10


exclude: ["README.md", "LICENSE", ".post-template", ".gitignore", "start.bat"]

